### ISSUE TITLE
Expanding the Frost Palette to support charts

### ISSUE THREAD

**Issue by mwskwong** [arcticicestudio/nord#127]
> Issue type: Feature

### Issue Type

Feature

## Description

I currently use Nord to build my dashboard-like web app. While I noticed the Frost palette has only 4 colours which is barely enough for charts. I hope the Frost Palette can be expanded to have around 5 - 8 colours.

**Comment by arcticicestudio** [comment]
Hi @matthewkwong2, Nord is a 16 colors palette by design to be compatible with applications like terminal that make use of the 16x colorspace of most shells like _Bash_ or _Zsh_. Like [described in Nord's official documentation][d], you can simply extend the palette on your own:

> Please note that these guidelines are “soft“ recommendations to describe the original idea of Nord!
They may be used in a modified form like e.g. different use cases for a specific color or with different shading options applied.

If you're using a CSS pre-processor like [Sass][] you can use color modification functions like [`lighten()`][sl] to create new variant and shade colors based on Nord's palettes.

A really great resource to learn more about the design and usage of color palettes is the [_Refactoring UI_][r] by @sschoger ([Twitter][tw-ss]) and @adamwathan ([Twitter][tw-aw] . Check out this preview about [“Building Your Color Palette”][p] if you don't want to buy the eBook. Both authors also post awesome designs and great tips on Twitter, check out their collection like [“Design Tips”][tw-c-dt] and [“Little UI Details”][tw-c-luid].

[d]: https://www.nordtheme.com/docs/colors-and-palettes
[r]: https://refactoringui.com
[p]: https://refactoringui.com/previews/building-your-color-palette
[tw-ss]: https://twitter.com/steveschoger
[tw-aw]: https://twitter.com/adamwathan
[tw-c-dt]: https://twitter.com/i/moments/879086180909764608
[tw-c-luid]: https://twitter.com/i/moments/880688233641848832?lang=en
[sass]: https://sass-lang.com
[sl]: https://sass-lang.com/documentation/modules/color#lighten
