### ISSUE TITLE
Port for Nova

### ISSUE THREAD

**Issue by GwynethLlewelyn** [arcticicestudio/nord#146]
> Issue type: *feature*
Related issues:

## Description

Panic Inc., the creators of [Coda](https://www.panic.com/coda/), for which a [Nord theme already exists](https://github.com/arcticicestudio/nord-coda), have moved on and launched their newest editor, [Nova](https://nova.app/). This is not really an 'upgrade' from Coda — it has been designed from scratch as a completely new product. As a consequence, 'old' themes (and extensions) will not work any more.

As part of the beta-testing effort, I have 'ported' the Nord theme to Nova, to the best of my abilities and understanding. Please take into account that a lot was done on a trial-and-error basis, looking at some of the existing themes/templates, and adapting as needed. It's still a work-in-progress, but stable enough to be used (I do that every day 😁 ).

If you have installed Nova already, you can get the theme directly from the built-in extension library (just search for `Nord`).

The web-based template library for Nova, set up by Panic Inc., also [has pointers to this Nord-based theme](https://extensions.panic.com/extensions/gwynethllewelyn/gwynethllewelyn.Nord/).

And the actual work being done is on [GitHub](https://github.com/GwynethLlewelyn/Nord.novaextension).

There are a few pending issues (as said, it's a work-in-progress!) but the theme/template is usable, and gives reasonably consistent results with syntax highlighting. Issue #94 (comment colour) is not implemented yet, I think, and I need to review the notes for [0.2.0](https://github.com/arcticicestudio/nord/releases/tag/v0.2.0) to see if I have applied all the changes correctly (I believe not!).

## Environment and Versions

* Nord version: mostly based on 0.2.0 (probably not 100% implemented correctly)
* OS: macOS Big Sur 11.0.1 Beta (20B5012d)

## References

Besides the already-mentioned references above:

[Panic Inc.'s guide to designing Nova themes](https://docs.nova.app/extensions/themes/)

**Comment by arcticicestudio** [comment]
Hi @GwynethLlewelyn :wave:, thanks for your contribution :+1:

I've added it to the [backlog][blc] and @-mention you as soon as I start working on it so you can track the progress or contribute ideas for this port project.

Please be aware that it may take some time for this port project to be implemented because there are already [60+ port project requests in the backlog][bl] and my free time is limited to work on the massive amount of issues & PRs. I currently focus on the [data transition of all port projects][dt] to the [new and shiny website and documentations][n] to finally [reduce the maintenance overhead, create a „single source of truth“ and increase the overall project quality][lp] :octocat:
Also take into account that I work as a software developer in the “real world“ and I hope you understand that the time to work on my projects may vary depending on my free time. :pray:

I'm also a bit worried about the future plans of the Nova creators regarding the licensing model.
This might be a problem later on when it comes to maintaining the port, e.g. adding new syntax highlighting, improving existing ones of fixing any problem. As long as there is no way for theme authors to use a trial ersion of the app I won't be able to support the port. That's one of the main problems when trying to support commercial products :unamused: 

Anyway, your own port will help other users it in the meantime and can also serve as bootstrap project for the official port later on by using it as fundamental code base.

[bl]: https://github.com/arcticicestudio/nord/projects/1#column-288113
[dt]: https://github.com/arcticicestudio/nord-docs/issues/133
[lp]: https://github.com/arcticicestudio/nord-docs/issues/1
[n]: https://www.nordtheme.com
[blc]: https://github.com/arcticicestudio/nord/projects/1#card-48892573

**Comment by GwynethLlewelyn** [comment]
Hm! AFAIK, there seems to be at least a 30-day trial available, at least [for the latest versions](https://download-cdn.panic.com/nova/). Earlier versions were mostly betas and release candidates and required no license to use; however, they were more than enough to allow me to do a quick-and-dirty port (the styling format, so far, hasn't changed).

But you're quite right otherwise — commercial products are always a problem. I just use Panic's products because, well, I've been a really loooooooong-time user of them...
