### ISSUE TITLE
Keycaps?

### ISSUE THREAD

**Issue by S1SYPHOS** [arcticicestudio/nord#148]
Hey there,
I just saw [this](https://candykeys.com/product/gmk-nord-base-kit) and was quite surprised - are there any left in your private stock? ;)

Cheers!

**Comment by arcticicestudio** [comment]
Hi @S1SYPHOS 👋🏼 

Even though they make use of the Nord colors, there has been absolutely no contact or information from their side provided to me. I'm also not a fan of (please don't blame me) these “loud and clunky“ keyboards 🙈
Also the price seems quite high for a small set of keys, but I guess everyone sees it differently.

To answer your question: There are none in my private stock since I'm in no way connected with the manufacturer. Maybe I'll get some sets for advertising reasons and because they (probably) were able to make money with my project without having to work on a new color palette on their own 😄

**Comment by S1SYPHOS** [comment]
It's a small manufacturer producing very limited amounts for group-buys (around 250/300 I think), so the price is quite high. I'm surprised they didn't even ask / tell you 😕

Thanks for answering, anyway. Keep up the good work!

S1SYPHOS

**Comment by axelitus** [comment]
Although it's always nice to do so, they are not required to ask/tell because of the license the palette is released with.

The keys look nice, though certainly pricey! Will be great advertising hehe
