### ISSUE TITLE
What is the color used for the background and headerbar for the nord website, should it be documented

### ISSUE THREAD

**Issue by sharpenedblade** [arcticicestudio/nord#164]
> Issue type: Documentation, and colors

On the nord website the header bar and page background are a darker shade of nord0., or a brighter shade of nord6. This color seems very usefully for many projects, so I think it should be documented.

**Comment by arcticicestudio** [comment]
Hi @hellosway :wave:

Nord is a set of colors which represent a base for project styles. While most official port projects try to only use these, Nord itself is not a strict documentation how to style your project bur rather provides [guidelines like “soft“ recommendations to describe the original idea of Nord][4]. I often refer to the fantastic [“Refactoring UI“][5] book which is one of my favorite design inspirations and resources. There's a preview called [“Building Your Color Palette“][3] which is useful to understand how to make use of a "static" color palette to build up on to create variations for your own project.
This also applies to [Nord's official website and documentations][6] which [derives colors from the base colors][1] as shared colors across multiple elements on the pages. As an example the [`Header` component][7] derives from these and [creates new accent colors][2] that are exclusive used by this component.
Creating modern and easy to use UIs (e.g. websites) with a limit of 16 colors is almost impossible, especially when providing features like [dark/light modes][8] which would make it impossible to ensure enough contrast across all the different elements. Therefore modern design derives shades, tones and variants from a base color set to build up on.

All of this means that there are many variants used across Nord's website which is impossible, and unnecessary, to document because each project has different use cases that require to adjust the variants.

[1]: https://github.com/arcticicestudio/nord-docs/blob/22758604f3b77aa217fa751751835cd2d6b250ee/src/styles/theme/colors/background.js
[2]: https://github.com/arcticicestudio/nord-docs/blob/22758604f3b77aa217fa751751835cd2d6b250ee/src/components/organisms/shared/styles.js
[3]: https://www.refactoringui.com/previews/building-your-color-palette
[4]: https://www.nordtheme.com/docs/colors-and-palettes
[5]: https://www.refactoringui.com
[6]: https://github.com/arcticicestudio/nord-docs
[7]: https://github.com/arcticicestudio/nord-docs/tree/b37ec8d6/src/components/organisms/core/Header
[8]: https://github.com/arcticicestudio/nord-docs/blob/22758604f3b77aa217fa751751835cd2d6b250ee/src/styles/theme/utils/themedMode.js

**Comment by arcticicestudio** [comment]
Closing this issue for now because this topic should be clarified, but feel free to reply if you think this requires more discussion or if you have questions.
