### ISSUE TITLE
Develop in a more "community" approach

### ISSUE THREAD

**Issue by saccarosium** [arcticicestudio/nord#179]
> Issue type: improvement

## Description

Currently the project as a hole is managed basecly by a single dude (@svengreb). This lead to a very slow managment of the project, and adds a lot of freaction for people, like myself, how would love to help manage and manetaine some of the repo and help writing docs and other stuff.
My solution would be to take a more "community" approach and start split the resposability from svengreb shoulders into other people (something like is done with dracula). 

## Potential Solution

1. Open channels of communication where discussing the managment of new ports and other develoment discussions
2. Start to open the doors to arcticicestudio to other willing developers and mantainers

**Comment by mgred** [comment]
Another solution would be to fork the project and give it some fresh air. It seems people are interested in new ports and improvements, hence it's a pity there's no attention from the sole maintainer.

**Comment by SomeGuyNamedMay** [comment]
agreed, Im a big fan of the theme but the lack of a pipeline for accepting ports is kind of disappointing

**Comment by SomeGuyNamedMay** [comment]
perhaps we could fork the project and use an approach like catppuccins?

**Comment by mgred** [comment]
> perhaps we could fork the project and use an approach like catppuccins?

What do you mean by that?

**Comment by SomeGuyNamedMay** [comment]
that was more of an example of a more active repo with more maintainers, but i do agree the repo should probably be forked

**Comment by saccarosium** [comment]
> perhaps we could fork the project and use an approach like catppuccins?

It a good idea, just read catppuccin's contribution guide and seem lovely.

Now If we wanna fork the project.. we do as a soft fork or an hard fork?

**Comment by SomeGuyNamedMay** [comment]
referencing the website? i dont have much experience in web dev but i could learn to try to help out.

**Comment by SomeGuyNamedMay** [comment]
if your referencing the ports then no id advocate for just forking those projects as well

**Comment by saccarosium** [comment]
Ok, we should clarify "fork che project". Because to me imply two things: or a soft fork approach (somethings like `gruvbox-community`) or a hard fork approach (something like `neovim`)

**Comment by SomeGuyNamedMay** [comment]
a soft fork is probably ideal, at least in my opinion

**Comment by SomeGuyNamedMay** [comment]
the only thing that would worry me about this approach is discoverability tbh

**Comment by saccarosium** [comment]
> the only thing that would worry me about this approach is discoverability tbh

Same, but I think for now is the best approach. Will see going forward if will change.

**Comment by SomeGuyNamedMay** [comment]
so is the plan to make a new nord-community organization through GitHub and push all our projects there? im not overly familiar with GitHub tbh as Ive only really ever contributed code to projects and haven't dealt with the maintenance aspect yet

**Comment by mgred** [comment]
> Now If we wanna fork the project.. we do as a soft fork or an hard fork?

Honestly, I don't really know the difference here. To me a fork is a fork. The code should finally live in another repository.

> so is the plan to make a new nord-community organization through GitHub and push all our projects there? 

I guess that's the way to do it. To me it makes sense to also _fork_ the ports. If they're - like here - in separate repos or all in one is organizational detail.

**Comment by saccarosium** [comment]
[Created](https://github.com/nord-community). Now I need some time for fork all the ports, and try to sync also all the issues.

**Comment by mgred** [comment]
@saccarosium may be that's a bit too fast, lets sit and think what are the goals and benefits, as well as the direction to go. I also would like to hear @svengreb, maybe there is a chance to use the existing infrastructure and project and just rehydrate what's already there...

**Comment by mgred** [comment]
There are also some organizations around the nord theme, so I guress there are (were) plans to gather more people around the project, see https://github.com/nordtheme and https://github.com/nordtheme-community

**Comment by svengreb** [comment]
Even if I tried to keep an explanation on this topic as short as possible, it would probably still be enough text for a book.
That's why books exist about [building and maintaining a community][4] that do not fit in a GitHub issue comment.
Nevertheless, let me try to summarize the conversation in this issue to provide some answer to your questions and assumptions. Please excuse a few sarcastic statements in advance, but if you have been working in the OSS for more than 15 years as well as on a professional basis in IT, unfortunately, this is often necessary because otherwise you will no longer be able to get a grip on the topics that are always rebellious.

@saccarosium

> (…) a very slow managment (…) adds a lot of freaction for people, like myself, how would love to help manage and manetaine some of the repo and help writing docs and other stuff [_sic_]

Could you elaborate of what is “managed slowly“?
People often make the mistake of only paying attention to “the outside“ and forget that they have no insight into “the inside“. I “manage“ the project on a daily basis, which means I have to dig through ~20+ GitHub notifications per day to keep up-to-date with conversations in various places like issues, PRs and discussions where most of them are “user problems“ that could have been fixed when reading the documentations or trying to get at least a minimum knowledge of the technology or project they tried to use. After that 10+ support/help request emails wait for me, so I repeat myself the next 100 times in 98% of the cases for things that could have been fixed when the human asking would have spend 5 minutes on their own. After that it's time to go through the [various official communities][5] to provide help, answer questions and moderate contributions at all because not everyone seems to have been taught the manners of interacting with other people, so people like me have to play the “kindergarten teacher“.
If required, the next steps are either one-time tasks like **paying costs for infrastructure from my own pocket for a project that can be used by everyone for free** or “managing“ **topics like preventing [the website from being shutdown due to too much traffic on free hosting plans][7]**.
When I then look at the clock, more than 2 hours of my day can be gone again, but I guess all of this does not count as “management“ because in a “cancel culture“ and “this does not procrastinate fast enough for me“ time things must always reach useless “trending“ metrics.

If you're more deeply into open source you'd know that the burden and burndown syndromes of project maintainers is way too high and, as many (GitHub) studies found out, [the “Maintainers are working harder than ever“][13] and that

> (…) developers inside an organization are still contributing code to their company’s projects at a much higher rate than external contributors.

which can be reflected to non-company driven projects 1:1. The [“Working in Public: The Making and Maintenance of Open Source Software“][9] must-read book describes this in 100% accuracy.

> (…) start split the resposability from svengreb [_sic_] (…)

That sounds a bit like you want to expropriate someone's work to grab it for yourself. Don't get me wring here, but unfortunately this is now a frequently seen phenomenon in the last couple of years in OSS because “newbies“ did not come into OSS with the same motivation like 10+ years ago but more of a “I want the stars“ approach (like useless “social“ platform love it and teach everyone). That's not meant to be mean, but if you'd go to your favorite coffee shop and tell the owner there that you will take over his duties immediately because you can do it better, my guess would be that he won't think it's that great.

Dividing work and distribute it onto “team members“ is what it is called in professional, or maybe better worded “experienced“, areas and this is of course the way for larger projects, but people often don't understand that _project != project_. There are [roughly 4 types of OSS projects][8] where Nord can be seen as a _Stadium_. There are thousands, or even hundreds of thousands users if you believe the statistics, but only 5% or less actively support or contribute instead of only consuming the project.

<p align="center"><img width="80%" alt="table of the 4 different types of open source projects" src="https://user-images.githubusercontent.com/13448100/208297883-2026cbe8-c356-41a1-b0d6-37696eff4bc7.png"></p>

In short this means I get hundreds of “Gimme! Gimme! Gimme!“ requests, but as soon as maintainer respond in a “you can contribute it on your own, I'll support you“ way, the authors of these requests are gone faster than lightning because now they have to spend their own free time and learn about things. This is a perfect reflection of the “I want if for free so that I can blame you for doing it wrong!“ times.
As hard as it sounds, but way too many people are driven again by the “I want to be a virtual star“ thought that runs through today's society like a disease. Please think twice before you want to copy someones work and publish it on your own, it can go in a completely wrong direction than initially thought.

I absolute love GitHub and it more or less my browsers start page, but over the last couple of years it also created some bad behaviors in the OSS world
All of this is absolutely accurate and perfectly written down in the [“Working in Public: The Making and Maintenance of Open Source Software“][9] book by [Nadia Eghbal][10] and this book is a 100% recommendation for everyone who'd want to get into open source more seriously. Also many of what I explained here, and how to prevent and improve it, can be found in the fantastic [“Open Source Guides“][11] (by GitHub) which is, in my opinion, a must-read for everyone (maintainers and contributors) in the open source ecosystem.

> (…) Open channels of communication where discussing the managment of new ports and other develoment discussions [_sic_] (…)

There are [official community platforms][5] for communication and "Nordies", of course not only for new ports but everything around Nord.

So here are some questions from my side to understand the problem in more detail and try to elaborate in it:

1. Why does a project, not managed by yourself, “friction“ you?
2. Who or what keeps you from writing docs and other stuff for a project that is open source and everyone can contribute?
3. If you want to “maintain“ a project, what is your exact goal other than contributing? (which can be done by everyone like mentioned in question Nr. 2)
4. What keeps you from using the existing community platforms?

@mgred

> (…) people are interested in new ports and improvements (…)

Of course they are, just like I explained above. People are only satisfied with something for less than 24h, and then they want the next shiny thing.
Just like for the questions above, I'd like to understand what keeps you from creating a port for your favorite application/project/etc. and publish it for others? This concept is one of the basic pillars of open source. Take some larger projects like Kubernetes as an example: everyone can use the APIs and [create CRDs][12] without the need to ask the maintainers as long as you adhere to the license model.

@SomeGuyNamedMy

> (…) lack of a pipeline for accepting ports is kind of disappointing (…)

Again, creating a new port seem like a easy task for everyone not involved in maintaining it, but it comes with a bunch of tasks and drains free time even more. You don't see the number of support & help requests popping up on a daily basis where most of them are just time consuming because it could have been solved within minutes when the author would be willing to use the brain on their own but wants to be spoon-feed for free instead.
Most of the time users request a port for their favorite upstream project by throwing the task at the maintainers and then disappears for ever when it has been provided. The maintainers are now left alone with the project, often not used to it at all because it was not one of the upstream projects they use, and the pile of issues and support requests keeps growing without everyone else who helps to actively maintain it. So basically the project was a stillbirth from the moment the repository was created.
People shouting "Gimme!" again and then they leave as soon as that means they have work to do themselves.

In short: “Official“ ports require knowledge and preparation to make it maintainable, otherwise it ends up in a stale state due to active contributors. This “phenomena“ is again also described in the [“Working in Public: The Making and Maintenance of Open Source Software“][9] book already mentioned above and it's another burden for people like me who already spend a lot of free time and _heartblood_ into OSS.

> (…) im not overly familiar with GitHub tbh as Ive only really ever contributed code to projects and haven't dealt with the maintenance aspect yet [_sic_] (…)

I'm sorry to say that, but this is a perfect example and describes this issue in total. It's like someone trying to fly an airplane when they can't even ride a bicycle.

**Summarizing the whole issue:**:

Asking for something you have absolutely no idea what's behind it is a pretty rash move.
Being a maintainer is not always fun and, also [well documented in the book mentioned multiple times above][9], can be very exhausting. I'm experienced enough in the open source ecosystem to know when to step aside for a while to fresh my energy and prevent burnouts, one of the most common problems in this system right now. Not only in OSS but almost everywhere by this deviant "ever faster" way of thinking of the whole world in many areas.
I've spend thousands of hours only in Nord and it's not easy when you work full time while trying to keep your “real life“ healthy with family, friends, sport and your other favorite free time activities.
Adding more “maintainer“ to a project is not a easy solution for this problem in OSS, but know your're facing the need to also manage “them“ in a way to coordinate the work, in addition to the tasks you already have right now. I tried to do this some years ago and it ended in a way that **they tried to merge changes that meet their own need**, but never checked it against the overall project goal and were gone after that too because they don't wanted to spend more time to help others anymore.
The people that contribute one-time are so called “drive-by contributors“ and these are almost 75% of the contributions globally in OSS. It's a small part of users of a project who want to see something changed and after that they are satisfied and appear again. Really active maintainers are rare and require by far more knowledge than “I used the project so gimme the commit permissions“.

Again, please never assume that a maintainer is “not active“ because they don't appear on bulls\*\*\* metrics like contribution graphs or post a comment for the sake of fulling the “never-ending timeline of new content“. I get headaches when I think about regular communications about legal topics and management tasks that came with publishing ports to distribution platforms. Being a maintainer also means to take care and responsibility like this.
ANother large topic are finances, which is something almost nobody thinks of when wanting to start a larger project, and this is also the point where most people block totally because now they not only have to spend their free time, but also their personal money. I won't go too deep into this topic, but be prepared for that if you want to be a maintainer.

Before taking action without thinking first I'd like you to ask yourself some questions and please answer them here in public so that we can understand and work on sharp corners in the Nord project together, just like I did since the beginning of the project:

1. Where do you miss the “community“ approach when there are [“official“ platforms for communication and interaction5][id] with others?
2. Do you really want to start to be **an active maintainer** with all the tasks and burdens that are to come or is your mood right now driven by the fact that you are frustrated that things are not fast enough, without thinking about “the other side“?
3. Why do you want to fork a project, decentralizing the source, instead of “simply“ contributing your changes or take action in communicating your proposals? Is there any problem that prevents it and, if yes, please describe it so that it can be resolved as fast as possible.
4. Which port do you miss that must absolute be maintained in an official manner but can not ne created by a Nor user instead?

A quick note, I started to write this at 10:55 +0100 which are now more than 2h (on the 4th advent 2022). This is a perfect example of how your free time will fade when you saddle yourself with more and more tasks by starting to “be a maintainer“.

**Some more quick-peeks for you, but this was also often mentioned in many other places in the Nord project:**

I plan large changes to the overall Nord project structure for almost 10 months now, including better task management and centralized community inclusion. My personal task time tracker says 1256h and roughly 12 minutes to organize, prepare nd document of the planned changes. Again, my free time “lost“ for other things.
The discoverability of community-driven projects is one part of it as I don't want to keep track of the whole _www_ to refer people to others ports and also want to provide a managed place for it. I never listed others projects because, after I did so multiple times, I got supper & help requests again because people are not able to read who created a project and “spammed“ me instead, blaming me afterwards because I said I don't support requests for others projects.
Thanks to the fantastic work of GitHub over the last couple of years, features like [sponsors][14] [^1] help me to keep the project running and prevent burnouts, so this is always a good way to support your favorite projects.

The plans & roadmap will be, hopefully, announced within the next weeks as the preparations are almost done.
If you plan to fork anything you're of course free to do so, but keep in mind that I won's recommend to refer to external projects due do mentioned reasons that I tried to cover in this (way too large again) comment.

[1]: https://github.com/saccarosium
[2]: https://github.com/mgred
[3]: https://github.com/SomeGuyNamedMy
[4]: https://press.stripe.com/get-together
[5]: https://www.nordtheme.com/community
[6]: https://www.reddit.com/r/nordtheme
[7]: https://answers.netlify.com/t/impending-account-suspension-due-to-unwanted-bandwidth-expansion-package/80752
[8]: https://project-types.github.io
[9]: https://press.stripe.com/working-in-public
[10]: https://github.com/nayafia
[11]: https://opensource.guide
[12]: https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources
[13]: https://octoverse.github.com/2022/how-companies-invest-in-open-source
[14]: https://github.com/sponsors/svengreb

[^1]: https://github.com/sponsors

**Comment by saccarosium** [comment]
Hey @svengreb,
Thanks for the long and detailed response. I will try to make more clear what I meant and where I stand.

> What keeps you from using the existing community platforms?

* the reddit community is more like sharing rices or uses of the pallete in some applications;
* on the keybase I entered this summer and the most recent message was like christmas greetings...;
* Slack and Discord are marked as coming soon™️;
* Spectrum was shutdown;
* on Stack Overflow there are 0 question or activity.

And I was interested in a community where we could discuss the development of the colorscheme or at least a more make discussion on the makings of the theme.

> Why does a project, not managed by yourself, “friction“ you?

I think a project, even thought is open, can make things harder to contributors. In the nord case is simply the very long waiting time. You are not the problem, you work really hard and do a very good job but it is simply unsustanable to manage a large project like nord alone, especcially since people wants port of software you don't use or care about.

> If you want to “maintain“ a project, what is your exact goal other than contributing? (which can be done by everyone like mentioned in question Nr. 2)

Supporting the users managing and filtering issues, try to make your life a little easier.

> Do you really want to start to be an active maintainer with all the tasks and burdens that are to come or is your mood right now driven by the fact that you are frustrated that things are not fast enough, without thinking about “the other side“?

Yeah absolutly!

> Which port do you miss that must absolute be maintained in an official manner but can not ne created by a Nor user instead?

An official Neovim port.

> The plans & roadmap will be, hopefully, announced within the next weeks as the preparations are almost done.
If you plan to fork anything you're of course free to do so, but keep in mind that I won's recommend to refer to external projects due do mentioned reasons that I tried to cover in this (way too large again) comment.

Looking forward to that!

P.S. I really like your work. It's not like I wanna steal your work, or other shit like that, I just want to help. It is why I felt in love with Open Source.

**Comment by mgred** [comment]
@svengreb thank you very much for your answer and thoughts as well as the in-depth explanation on how much effort you put into the project, I think we all appreciate this a lot!!

Reading this issue again, I'd say this escalated quickly :smile: I'm sure nobody wants to steal from you.

**Comment by SomeGuyNamedMay** [comment]
i dont have anything to add to saccarosium. i agree with everything he said

**Comment by mgred** [comment]
@svengreb thank you very much for your answer and thoughts as well as the in-depth explanation on how much effort you put into the project, I think we all appreciate this a lot!!

Reading this issue again, I'd say this escalated quickly :smile: I'm sure nobody wants to _steal_ from you.

> Just like for the questions above, I'd like to understand what keeps you from creating a port for your favorite application/project/etc. and publish it for others? 

Short answer: Nothing! But I like the idea to have a central place where all ports come together, although they do not need to belong to the project as the official ones do. Maybe there is a list for _official_ (supported by you) and _unofficial_ ports. Something like a single entry point for people who want to explore already existing things.

> ... emails wait for me, so I repeat myself the next 100 times in 98% of the cases for things that could have been fixed when the human asking would have spend 5 minutes on their own.

This is absolutely frustrating and exhausting, but maybe also a pointer that there is a lack of guidance or clearness in the documentation. No blame, though.

> The plans & roadmap will be, hopefully, announced within the next weeks as the preparations are almost done.

I'm excited to hear about this. Personally, I would like to have some kind of a roadmap to see what is the direction this project is going. What are the plans for the future or features to come and help with. 

@SomeGuyNamedMy, @saccarosium maybe we could create a repository, or an orga where we can gather (unofficial) nord-ports.  A collection that is not a rivalry but an addition to the official ones. We could also encourage devs to create more ports or try to give guidance and best practice.

**Comment by saccarosium** [comment]
> @SomeGuyNamedMy, @saccarosium maybe we could create a repository, or an orga where we can gather (unofficial) nord-ports. A collection that is not a rivalry but an addition to the official ones. We could also encourage devs to create more ports or try to give guidance and best practice.

Could be an idea but at this point I think is better to wait the roadmap and plan accordantly.

**Comment by saccarosium** [comment]
I think is time to close this issue. A good way to see how the project will go foward is [this post](https://github.com/orgs/nordtheme/discussions/183) in the nordtheme github's discussion.
