### ISSUE TITLE
Differences between JetBrains theme and the VS Code theme.

### ISSUE THREAD

**Issue by gino** [arcticicestudio/nord#239]
Hello,

I am wondering if this is a known issue but if I compare the JetBrains Nord theme to the Nord theme for VSCode, some colors do not look the same. Is this a known issue or is there a way (without customizing a lot) that I could achieve the same in VS Code?

## Screenshot
On the left side we have PhpStorm and on the right side we have VS Code.

![image](https://user-images.githubusercontent.com/23482089/77248432-9a8ba480-6c39-11ea-8329-6ab52230d32a.png)

The PhpStorm variant has a couple of purple/pink accents which I do not have in the VS Code one, unfortunately.

**Comment by arcticicestudio** [comment]
Hi @gino :wave:, thanks for your contribution :+1:

I guess this might be related to https://github.com/arcticicestudio/nord-jetbrains/pull/121. There were severals problems regarding the defined theme keys in the _Nord JetBrains_ port project due to changes between IDE versions. An example problem reported by a user is https://github.com/arcticicestudio/nord-jetbrains/issues/115 where functions in _WebStorm_ used the color of _WebStorm_'s default theme instead of _Nord_.
If your _PHPStorm_ setup is also affected by this problem please try to re-install the _Nord_ theme plugin and also follow the instructions posted in https://github.com/arcticicestudio/nord-jetbrains/issues/115.

**Comment by arcticicestudio** [comment]
@gino Did the instructions helped to solve the problem?
