### ISSUE TITLE
Xcode theme?

### ISSUE THREAD

**Issue by ornithocoder** [arcticicestudio/nord#27]
Hello. Nord is simply amazing and I'm currently using it on vim and macOS' Terminal. Do you have any plans for releasing an official Nord theme for Xcode?

I'm currently using a heavily inspired theme I created. It's based on the official theme for vim.

<img width="1433" alt="screen shot 2017-04-07 at 9 14 42 am" src="https://cloud.githubusercontent.com/assets/19753339/24789350/dd12a076-1b72-11e7-9d88-512182b2c919.png">

**Comment by ornithocoder** [comment]
I've used the macOS Color Picker for applying the colors to the Xcode theme, but first I had to convert a native color palette (src/native) to macOS's native palette format (.clr)

![screen shot 2017-04-07 at 9 19 26 am](https://cloud.githubusercontent.com/assets/19753339/24789509/aebabd98-1b73-11e7-927f-d9dfcf75f684.png)

**Comment by arcticicestudio** [comment]
Thanks for your proposal 👍 
I'll add the Xcode port project to #18 and @-mention you as soon as I start working on it in the backlog ticket.
Please note that it may take some time because there are many tickets with requests and other proposals in the queue. Also take into account that I work as a software developer in the "real world" and I hope you understand that the time to work on my projects may vary depending on my freetime.

Thanks for the note on the `.clr` native color palette, I will add it as a new feature to Nord 😄

**Comment by ornithocoder** [comment]
That's awesome. Thanks @arcticicestudio!

**Comment by arcticicestudio** [comment]
🚢 Shipped with initial  release version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-xcode/releases/tag/v0.1.0).
