### ISSUE TITLE
Highlight.js Theme

### ISSUE THREAD

**Issue by pspeter3** [arcticicestudio/nord#38]
Adding a highlight.js theme would be great for syntax highlighting on the web.

**Comment by arcticicestudio** [comment]
Thanks for your proposal 👍 
I'll add it as a port project to #18 and @-mention you as soon as I start working on it in the backlog ticket so you can track the progress or contribute ideas for this port project.

Please note that it may take some time because there are many tickets with requests and other proposals in the queue. Also take into account that I work as a software developer in the "real world" and I hope you understand that the time to work on my projects may vary depending on my freetime. :octocat:

**Comment by arcticicestudio** [comment]
@pspeter3  Sorry for the long delay, I've had almost no free time to work on my projects.

The [Nord highlight.js](https://github.com/arcticicestudio/nord-highlightjs) repository has been created and the initial version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-highlightjs/releases/tag/v0.1.0) has been released.

The package is also [available on npm](https://www.npmjs.com/package/nord-highlightjs) to simplify the usage in Node based projects.

**Comment by pspeter3** [comment]
No worries! Thanks for doing that 😄
