### ISSUE TITLE
Slack theme

### ISSUE THREAD

**Issue by pspeter3** [arcticicestudio/nord#39]
The color scheme looks great and having it for Slack would be great as well. My best attempt was `#2E3440,#3B4252,#434C5E,#D8DEE9,#3B4252,#D8DEE9,#8FBCBB,#81A1C1`

**Comment by arcticicestudio** [comment]
Thanks for your proposal 👍 
I'll add it as a port project to #18 and @-mention you as soon as I start working on it in the backlog ticket so you can track the progress or contribute ideas for this port project.

Please note that it may take some time because there are many tickets with requests and other proposals in the queue. Also take into account that I work as a software developer in the "real world" and I hope you understand that the time to work on my projects may vary depending on my freetime. :octocat:

**Comment by cobrabr** [comment]
I've made an attempt at a Nord theme for Slack as well: `#2E3440,#3B4252,#5E81AC,#ECEFF4,#434C5E,#D8DEE9,#A3BE8C,#D08770`.

This is what it looks like:
![image](https://user-images.githubusercontent.com/724969/27154248-5cb6c3d6-5122-11e7-8455-9731d89a995c.png)

One way of quickly testing themes is using [SlackThemes.net](http://slackthemes.net/) -- you can select themes or manually enter the colour values in the text box at the bottom.

**Comment by pbnj** [comment]
**A slight modification:**
![screen shot 2017-08-28 at 11 49 24 am](https://user-images.githubusercontent.com/6811830/29788334-0d237576-8be7-11e7-954e-b41adb7a2e17.png)

**Breakdown:**
- Column BG: `nord1`
- Menu BG Hover: `nord0`
- Active Item Text: `nord6`
- Hover Item: `nord0`
- Text Color: `nord6`
- Active Presence: `nord14`
- Mention Badge: `nord11`

![screen shot 2017-08-28 at 11 50 52 am](https://user-images.githubusercontent.com/6811830/29788369-2f81e508-8be7-11e7-968e-27477052f251.png)


Custom Slack Theme one-liner: `#3B4252,#2E3440,#5E81AC,#ECEFF4,#2E3440,#ECEFF4,#A3BE8C,#BF616A`

_EDIT:_
- Adding link for users to try out theme in browser: http://slackthemes.net/#/custom#3B4252,2E3440,5E81AC,ECEFF4,2E3440,ECEFF4,A3BE8C,BF616A

**Comment by pspeter3** [comment]
So is it red instead of orange?

**Comment by cobrabr** [comment]
@pspeter3 -- that, and the background and hover colours are inverted.

**Comment by pbnj** [comment]
@pspeter3 - sorry my comment was not clear. @cobrabr is correct.
Visualizations may help:

| @pspeter3  | @cobrabr  | @petermbenjamin |
| -  | - | - |
![@pspeter3](https://user-images.githubusercontent.com/6811830/29792574-a5bdc8a0-8bf5-11e7-834b-9259914bafac.png) | ![@cobrabr](https://user-images.githubusercontent.com/6811830/29792590-b0d32a96-8bf5-11e7-90a6-9aaa27c4b572.png) | ![@petermbenjamin](https://user-images.githubusercontent.com/6811830/29792613-c227b050-8bf5-11e7-9256-2deb283f0f90.png) |
| [Try it in browser](http://slackthemes.net/#/custom#2E3440,3B4252,434C5E,D8DEE9,3B4252,D8DEE9,8FBCBB,81A1C1) | [Try it in browser](http://slackthemes.net/#/custom#2E3440,3B4252,5E81AC,ECEFF4,434C5E,D8DEE9,A3BE8C,D08770) | [Try it in browser](http://slackthemes.net/#/custom#3B4252,2E3440,5E81AC,ECEFF4,2E3440,ECEFF4,A3BE8C,BF616A) |

**Comment by pspeter3** [comment]
Yeah the iterated ones look way better than my original. I think I was largely trying to follow the documentation in the README

**Comment by arcticicestudio** [comment]
Sorry for the long delay, I've almost had no free time to work on my projects.

Currently thinking on how to build this port project since there is no file format to provide themes, but manually setting the colors. The repository should only contain a README.md to document the install steps, the way to preview the theme using [slackthemes.net][st] and references to the official Slack documentation on [how to customize the theme][slack-docs].

I'll also submit a PR to the [slackthemes.net repository][st-gh] to add it to the available themes.

[st]: http://slackthemes.net
[st-gh]: https://github.com/paracycle/slackthemes
[slack-docs]: https://get.slack.help/hc/en-us/articles/205166337-Customize-your-Slack-theme

**Comment by arcticicestudio** [comment]
The [Nord Slack](https://github.com/arcticicestudio/nord-slack) repository is now available and the initial version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-slack/releases/tag/v0.1.0) has been released.

![](https://raw.githubusercontent.com/arcticicestudio/nord-docs/develop/assets/images/ports/slack/overview.png)

**Comment by lokesh-krishna** [comment]
Could you please add this project to the readme to improve discoverability?

**Comment by arcticicestudio** [comment]
Currently there are several new port projects missing in the Nord documentation. I'll add them as soon as I've created the banners.

**Comment by tborychowski** [comment]
I've created this repo for the  nord fanatics who (like me) prefer to have the full dark theme:
https://github.com/tborychowski/slack-nord-theme

:-)

**Comment by arcticicestudio** [comment]
@tborychowski Looks nice, maybe a proposal should be submitted to the Slack team so they extend their current theming API. From quickly looking into the code it seems like this will break with each Slack update so it would be nice if there are new theme fields to style more sections of the UI.

**Comment by tborychowski** [comment]
@arcticicestudio yes. This hack needs to be applied after every update of the slack app.
I asked slack  team couple of times  about supporting better theming or even macos dark mode, but the answer  is always the same: "we're thinking about it" :-)
