### ISSUE TITLE
Alacritty theme

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/nord#44]
There is this new and awesome terminal being developed and was wondering if theme for it could be added?

https://github.com/jwilm/alacritty

**Comment by arcticicestudio** [comment]
Thanks for your proposal 👍 
I'll add it as a port project to #18 and @-mention you as soon as I start working on it in the backlog ticket so you can track the progress or contribute ideas for this port project.

Please note that it may take some time because there are many tickets with requests and other proposals in the queue. Also take into account that I work as a software developer in the "real world" and I hope you understand that the time to work on my projects may vary depending on my freetime. :octocat:

In the meantime you can use the [unofficial color scheme](https://github.com/jwilm/alacritty/wiki/Color-schemes#nord) posted by @heliostatic in the Alacritty project wiki :smile:

**Comment by ghost** [comment]
Awesome, thank you! And yes, that's what I'm using for the time being ;)

**Comment by arcticicestudio** [comment]
@gutigen Sorry for the delay, I've had almost no free time to work on my projects.

The [Nord Alacritty](https://github.com/arcticicestudio/nord-alacritty) repository has been created and the initial version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-alacritty/releases/tag/v0.1.0) has been released.

**Comment by ghost** [comment]
@arcticicestudio totally fine, thanks for update ;)
