### ISSUE TITLE
PHPStorm

### ISSUE THREAD

**Issue by onizuka-dev** [arcticicestudio/nord#48]
I was wondering if can be any support for PHPStorm, my favorite IDE

**Comment by arcticicestudio** [comment]
It's already supported, but the port project is named [Nord IntelliJ IDEA Syntax](https://github.com/arcticicestudio/nord-intellij-idea-syntax). There are plans to rename it to something like *Nord JetBrains* to clarify its use cases since the theme format is supported by all IDE's based on IntelliJ, so actually all these awesome products from JetBrains :laughing:
