### ISSUE TITLE
Emacs theme?

### ISSUE THREAD

**Issue by jinnovation** [arcticicestudio/nord#6]
Beautiful color palette. Was wondering if there's any plan for an Emacs theme?

**Comment by arcticicestudio** [comment]
Thanks, there are indeed plans to port it to Emacs next to many other applications, but I'm currently too busy to start working on it.
I'll mention you in the issue/PR as soon as it it implemented.

**Comment by arcticicestudio** [comment]
I created some project branding assets for upcoming port projects (vim, gedit, eclipse, iterm2 ...) including emacs, but I think I've to move it downwards the priority list since it seems to be a lot of work to create a good  quality theme that supports as many emacs features as possible.

I've never used emacs so I checked out their wiki and some theme collection websites including the repositories of the most popular themes.
Since some theme files are more than 5000 lines (!) there are many things that must be considered which includes support for package archives like [MELPA](https://melpa.org/#/) and the [marmalade-repo](https://marmalade-repo.org/).

**This doesn't mean that there will never be a port**, but I have to postpone it to an unknown time when I've finished most of my planned projects and got some freetime to understand how their theme system works.

**Comment by bobbypriam** [comment]
Hi, I'm loving this color palette, particularly the low-contrast you're using while still being distinguishable. It makes writing code less straining. Thanks!

I've been learning to use Spacemacs lately (it's a great editor!) and bummed that there's still no official Emacs port for Nord, so I took the liberty of creating one for my own use. [You can see the repo here](https://github.com/bobbypriambodo/nord-spacemacs). The base template was generated using [ThemeCreator](http://mswift42.github.io/themecreator/) tool.

It's still lacking package manager support, though, and there might be color mistakes here and there. I plan to improve it while I keep using Spacemacs for my day-to-day tasks. You're free to use it as a starting point (or scrap it altogether) should you do implement the official port later 🙂

**Comment by apierz** [comment]
I like Nord theme and use Emacs so I've put together an Emacs theme with fairly good support for a lot of modes. I've tried to adhere to the vim color choices wherever possible.

<img width="721" alt="screen shot 2017-02-08 at 3 45 35 pm" src="https://cloud.githubusercontent.com/assets/7518085/22762887/948e695e-ee16-11e6-80ef-4669f64cda57.png">
<img width="721" alt="screen shot 2017-02-08 at 3 52 01 pm" src="https://cloud.githubusercontent.com/assets/7518085/22762897/a1f2d238-ee16-11e6-83c9-465adee4dde0.png">

[Here](https://github.com/apierz/nord-emacs) is my repo for the theme file. If you think this has potential as the official Nord theme for Emacs I'd be happy to keep working on it and take care of adding a real README, maintaining it on MELPA, etc.

**Comment by arcticicestudio** [comment]
@bobbypriambodo @apierz  Thanks for your contributions 👍 and sorry for the late reply, I've been busy at work.
Since Nord Emacs is also already a planned port project I'll check out your provided code and see what can be merged into the official port 😉
You can find more information in the epic issue #18 in the **Editors & IDEs** section.
I'll notify all participants in this issue as soon as the specific backlog issue is created so you can track the progress or contribute ideas for this port project.

@bobbypriambodo I've never used Emacs neither Spacemacs productively and only installed it to create the port project so I've to see if the theme could be used for both Emacs and Spacemacs.

@apierz Your port looks nice and I'll definitely check your code to manually integrate it into the official port. Unfortunately, I can not list it as the official port project since I've already started the official port as described in the epic issue #18 in the *Development Process* section. There are various unofficial ports for each port project and this would lead to a unmaintainable cluster of repositories.
As soon as the official port is available you can feel free to create PRs so the theme improves while keeping everything centralized for all users 😉

**Comment by apierz** [comment]
Ok. I've made some recent changes to my version to make the terminal colors show appropriately and ensure that it works fine when installed from MELPA.

**Comment by arcticicestudio** [comment]
### <img src="https://www.gnu.org/software/emacs/favicon.png" width=16 height=16/> Emacs

🏁 Process ▮▮▮▮▮▮▮▮▮▮ `100%`
*ETA*: 2017-03-25 ✔️ 

❯ **Title**: Nord Emacs
❯ **Project**: [`nord-emacs`](https://github.com/arcticicestudio/nord-emacs)
❯ **Initial Release Version**: 🏷 [0.1.0](https://github.com/arcticicestudio/nord-emacs/releases/tag/v0.1.0)

I've created the repository and created some tickets for planned features and :package: package supports like
**Syntax**
  - [JavaScript Mode](https://github.com/arcticicestudio/nord-emacs/issues/7)
  - [Org Mode](https://github.com/arcticicestudio/nord-emacs/issues/2)
  - [Markdown Mode](https://github.com/arcticicestudio/nord-emacs/issues/3)

**UI**
  - [Git Gutter](https://github.com/arcticicestudio/nord-emacs/issues/4)
  - [Evil Mode](https://github.com/arcticicestudio/nord-emacs/issues/5)
  - [MU4E](https://github.com/arcticicestudio/nord-emacs/issues/6)

I'll add more tickets to support most of the popular packages. Also please feel free to tell me your favorite packages you'd like to see being included.

The project will be available from <img src="https://melpa.org/favicon.ico" width=16 height=16/> [MELPA](https://melpa.org) and the [marmelade-repo](https://marmalade-repo.org) and soon as the initial release version has been released.

**Comment by arcticicestudio** [comment]
🚢 Shipped initial release version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-emacs/releases/tag/v0.1.0)!

Nord Emacs will be available on MELPA as soon as [melpa/melpa PR #4655](https://github.com/melpa/melpa/pull/4655) gets merged.

I think the initial version covers a good amount of popular packages, but you can create PR's for whatever packages or improvements you'd like to see in the official port project.

/cc @jinnovation @bobbypriambodo @apierz

**Comment by arcticicestudio** [comment]
The PR has been merged and [nord-theme](https://melpa.org/#/nord-theme) is now available from MELPA.
