### ISSUE TITLE
Pycharm extension

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/nord#63]
Hello , 

your theme is awesome. is this available for pycharm? if not, can you please provide the support.

Thanks in Advance,
Aravind

**Comment by arcticicestudio** [comment]
There is already a port project named [Nord IntelliJ IDEA Syntax][nord-int]. Since all these awesome JetBrain products are based on the IntelliJ IDEA engine the theme can be used for all IDEs.

Note that the project will be renamed to *Nord JetBrains Editor* (repository name `nord-jetbrains-editor`) as also [announced on Twitter][t-rename] including support for the new awesome feature to [export IntelliJ editor themes as plugins][jb-blog] ([tweet][t-jar])

[nord-int]: https://github.com/arcticicestudio/nord-intellij-idea-syntax
[t-rename]: https://twitter.com/arcticicestudio/status/937664182895472640
[t-jar]: https://twitter.com/arcticicestudio/status/937663505523724288
[jb-blog]: https://blog.jetbrains.com/platform/2017/12/export-intellij-editor-themes-as-plugins/

**Comment by ghost** [comment]
Thank you. I found it and installed. It is working great.
