### ISSUE TITLE
Port for Steam

### ISSUE THREAD

**Issue by Mauladen** [arcticicestudio/nord#99]
The theme of Nord for the well-known Steam

![1](https://user-images.githubusercontent.com/12824589/37004487-9e0efa80-20e1-11e8-8ab8-295bff13dbf4.PNG)

![2](https://user-images.githubusercontent.com/12824589/37004492-a119d5ec-20e1-11e8-9f9a-2d0f357f3b9a.PNG)

![3](https://user-images.githubusercontent.com/12824589/37004500-a2fc272a-20e1-11e8-855f-9e5db768b064.PNG)

[Nord.zip](https://github.com/arcticicestudio/nord/files/1782915/Nord.zip)

**Comment by arcticicestudio** [comment]
Thanks for your contribution 👍 

Sorry for the delay, I've had no free time (job :man_health_worker:, study :book:, life :weight_lifting_man: etc.) to work on my or any other :octocat: OSS project (see Tweets :bird: from [April][t-april] and [June][t-june]), but from the beginning of July I finished my studies and can [finally spend time on OSS again][t-back] :green_heart:

I've added it to the [backlog][] and @-mention you as soon as I start working on it so you can track the progress or contribute ideas for this port project.

Please note that it may take some time because there are many other issues over many other port projects with requests and proposals waiting in the queue. I'm currently also very busy on working and prototyping on the [nord-docs][] to finally have a „single source of truth“ for Nord and all related data. :octocat:

[backlog]: https://github.com/arcticicestudio/nord/projects/1
[nord-docs]: https://github.com/arcticicestudio/nord-docs/issues/1
[t-april]: https://twitter.com/arcticicestudio/status/987753414342914049
[t-june]: https://twitter.com/arcticicestudio/status/1004777280646844417
[t-back]: https://twitter.com/arcticicestudio/status/1010013091793256448

**Comment by Mauladen** [comment]
@arcticicestudio At the moment, the topic is no longer relevant after a major upgrade of Steam
